export default {
  COLLECTIONS_INCLUDE: 'COLLECTIONS_INCLUDE',
  COLLECTIONS_ITEM_SAVE: 'COLLECTIONS_ITEM_SAVE',
  COLLECTIONS_ITEM_DELETE: 'COLLECTIONS_ITEM_DELETE',
  MENU_ADD_COLLECTIONS: 'MENU_ADD_COLLECTIONS',
}
