export default {
  COLLECTIONS_INCLUDE: 'COLLECTIONS_INCLUDE',
  COLLECTIONS_ITEM_SAVE: 'COLLECTIONS_ITEM_SAVE',
  COLLECTIONS_ITEM_DELETE: 'COLLECTIONS_ITEM_DELETE',
  VALUES_ITEM_SAVE: 'VALUES_ITEM_SAVE',
  STORE_SAVING: 'STORE_SAVING',
  STORE_SUCCESS: 'STORE_SUCCESS',
  STORE_FAILURE: 'STORE_FAILURE',
}
